name: Hello Workflow

on:
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello GitHub Actions Successfully Running!"
